# Generate Puzzle-8 instances with the goal state at depth “d”.

In [1]:
# for 1 (E)

def in_depth(unique,current):
    subNode=[]
    child=[]
    newchild = 0
 
    
    for i in range(len(unique)-current,len(unique)):
        subNode =[]
        subNode.extend(unique[i])
        node = []
        node.extend(unique[i])
        getZeroLocation=node.index(0)+1
        
        
        if getZeroLocation+3<=9:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)+3]
            subNode[node.index(0)+3]=temp
            
            if subNode not in (unique):
                child.append(subNode)
                newchild+=1    
            subNode =[]
            subNode.extend(unique[i])

            
        if getZeroLocation-3>=1:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)-3]
            subNode[node.index(0)-3]=temp
            if subNode not in (unique):
                child.append(subNode)
                newchild+=1
            subNode =[]
            subNode.extend(unique[i])
            
           
            
        if (getZeroLocation%3)!=1:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)-1]
            subNode[node.index(0)-1]=temp
            if subNode not in (unique):
                child.append(subNode)
                newchild+=1
            subNode =[]
            subNode.extend(unique[i])
            

            
        if (getZeroLocation%3)!=0:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)+1]
            subNode[node.index(0)+1]=temp
            if subNode not in (unique):
                child.append(subNode)
                newchild+=1
            subNode =[]
            subNode.extend(unique[i])

    
    return newchild,child
            





In [3]:
# for 1(E) main

import math,random,time
import numpy as np
import sys

start = np.array([2,8,3,1,6,4,7,0,5])
node =list(start)
j=0
unique = [1]
unique.append(node)
depth = int(input("Enter the depth:"))
current =1
begin = time.time()

while j<depth:
    
    newchild,child = in_depth(unique,current)
    current =newchild
    unique.extend(child)
    j+=1
    print("in depth",j,"goals are",newchild)
    

print("\n")
for i in range(len(child)):
        print(np.array(child[i]).reshape(3,3))
        print("\n")
    
end = time.time()
print("total time is:",end-begin,"seconds")

print("total numbers of node",len(unique))
total_size = sys.getsizeof(child) + sys.getsizeof(node) + sys.getsizeof(unique)
print("memory size:",total_size,"bytes")



Enter the depth:4
in depth 1 goals are 3
in depth 2 goals are 5
in depth 3 goals are 10
in depth 4 goals are 14


[[1 2 3]
 [0 8 4]
 [7 6 5]]


[[2 3 4]
 [1 8 0]
 [7 6 5]]


[[2 8 3]
 [7 1 4]
 [6 0 5]]


[[8 0 3]
 [2 1 4]
 [7 6 5]]


[[2 8 3]
 [1 4 5]
 [7 0 6]]


[[2 0 8]
 [1 4 3]
 [7 6 5]]


[[8 0 3]
 [2 6 4]
 [1 7 5]]


[[2 8 3]
 [6 7 4]
 [1 0 5]]


[[2 0 3]
 [6 8 4]
 [1 7 5]]


[[2 8 3]
 [6 4 0]
 [1 7 5]]


[[2 0 8]
 [1 6 3]
 [7 5 4]]


[[2 8 3]
 [1 5 6]
 [7 0 4]]


[[2 0 3]
 [1 8 6]
 [7 5 4]]


[[2 8 3]
 [0 1 6]
 [7 5 4]]


total time is: 0.036980628967285156 seconds
total numbers of node 34
memory size: 824 bytes


# for path


In [2]:
#Load its magic function
%load_ext memory_profiler
from memory_profiler import profile
%memit x = 10+5



peak memory: 47.63 MiB, increment: 0.25 MiB
