# Considering the cost associated with every move to be the same (uniform cost), write a function which can backtrack and produce the path taken to reach the goal state from the source/ initial state.


In [2]:
# for D back track

def in_depth(unique,current,parent_idx,final,ans):
    subNode=[]
    child=[]
    newchild = 0
 
    
    for i in range(len(unique)-current,len(unique)):
        subNode =[]
        subNode.extend(unique[i])
        node = []
        node.extend(unique[i])
        getZeroLocation=node.index(0)+1
        
        if getZeroLocation+3<=9:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)+3]
            subNode[node.index(0)+3]=temp
            
            if subNode not in (unique):
                child.append(subNode)
                parent_idx.extend([i])
                newchild+=1    
            
            if final==subNode:
                ans=False
                break
                
            subNode =[]
            subNode.extend(unique[i])
            

            
        if getZeroLocation-3>=1:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)-3]
            subNode[node.index(0)-3]=temp
            if subNode not in (unique):
                child.append(subNode)
                parent_idx.extend([i])
                newchild+=1
                
            if final==subNode:
                ans=False
                break
                
            subNode =[]
            subNode.extend(unique[i])
            
            
           
            
        if (getZeroLocation%3)!=1:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)-1]
            subNode[node.index(0)-1]=temp
            if subNode not in (unique):
                child.append(subNode)
                parent_idx.extend([i])
                newchild+=1
            if final==subNode:
                break
                
            if final==subNode:
                ans=False
                break
            subNode =[]
            subNode.extend(unique[i])
            

            
        if (getZeroLocation%3)!=0:
            
            temp=subNode[node.index(0)]
            subNode[node.index(0)]=subNode[node.index(0)+1]
            subNode[node.index(0)+1]=temp
            if subNode not in (unique):
                child.append(subNode)
                parent_idx.extend([i])
                newchild+=1
            
            if final==subNode:
                ans=False
                break
            subNode =[]
            subNode.extend(unique[i])

    
    return newchild,child,ans
            

Main method for find the path using back track.

In [5]:
# for D back track

import math,random
import numpy as np

start = np.array([2,8,3,1,6,4,7,0,5])
node =list(start)
f =np.array([8,3,0,2,6,4,1,7,5])
final =list(f)

ans = True

unique = []
parent_idx = [-1]
unique.append(node)
current =1

while ans:
    
    newchild,child,ans = in_depth(unique,current,parent_idx,final,ans)
    current =newchild
    unique.extend(child)
    
    
idx= len(unique)-1
print("Goal state:\n")
while idx!=-1:
    print(idx)
    print(np.array(unique[idx]).reshape(3,3))
    print("\n")
    
    idx = parent_idx[idx]

print("|^^initial state ^^|")    


Goal state:

46
[[8 3 0]
 [2 6 4]
 [1 7 5]]


25
[[8 0 3]
 [2 6 4]
 [1 7 5]]


15
[[0 8 3]
 [2 6 4]
 [1 7 5]]


7
[[2 8 3]
 [0 6 4]
 [1 7 5]]


2
[[2 8 3]
 [1 6 4]
 [0 7 5]]


0
[[2 8 3]
 [1 6 4]
 [7 0 5]]


|^^initial state ^^|
